"use client";
import {useEffect,useState} from"react";import{Bot,ChevronLeft,Copy,LoaderCircle,Radio,Shield,Swords,Users}from"lucide-react";
type Mode="menu"|"solo"|"quick"|"friend"|"room";type Side="pitch"|"bat";type Choice={kind:string;zone:string;style:string};type MatchState={id:string;status:string;inning:number;half:"top"|"bottom";outs:number;balls:number;strikes:number;homeScore:number;awayScore:number;bases:number[];role:"home"|"away";myReady:boolean;opponentReady:boolean;message:string;lastPlay?:{pitch:Choice;bat:Choice;result:string}|null};
const pitchKinds=["직구","슬라이더","체인지업"],batKinds=["직구","변화구","아무거나"],zones=["몸쪽","가운데","바깥쪽"];function getPlayer(){let x=localStorage.getItem("dd-player");if(!x){x=crypto.randomUUID();localStorage.setItem("dd-player",x)}return x}
export default function Home(){const[mode,setMode]=useState<Mode>("menu"),[player]=useState(()=>typeof window==="undefined"?"":getPlayer()),[nickname,setNickname]=useState("루키"),[code,setCode]=useState(""),[roomCode,setRoomCode]=useState(""),[match,setMatch]=useState<MatchState|null>(null),[busy,setBusy]=useState(false),[choice,setChoice]=useState<Choice>({kind:"직구",zone:"가운데",style:"정면승부"}),[solo,setSolo]=useState({inning:1,outs:0,balls:0,strikes:0,me:0,ai:0,bases:[0,0,0],message:"플레이 볼! 첫 승부를 준비하세요.",history:[]as string[]});
useEffect(()=>{if(mode!=="room"||!match?.id||!player)return;const id=match.id,t=setInterval(async()=>{const r=await fetch(`/api/game?gameId=${id}&playerId=${player}`,{cache:"no-store"});if(r.ok)setMatch(await r.json())},900);return()=>clearInterval(t)},[mode,match?.id,player]);
async function matchmaking(action:"quick"|"create"|"join"){setBusy(true);try{const r=await fetch("/api/game",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,playerId:player,nickname,code:code.toUpperCase()})}),d=await r.json();if(!r.ok)throw Error(d.error);if(d.code)setRoomCode(d.code);setMatch(d.game);setMode("room")}catch(e){alert(e instanceof Error?e.message:"매칭 실패")}finally{setBusy(false)}}
async function submitOnline(){if(!match)return;setBusy(true);const side:Side=((match.half==="top"&&match.role==="away")||(match.half==="bottom"&&match.role==="home"))?"bat":"pitch";try{const r=await fetch("/api/game",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"play",gameId:match.id,playerId:player,side,choice})}),d=await r.json();if(!r.ok)throw Error(d.error);setMatch(d.game)}catch(e){alert(e instanceof Error?e.message:"오류")}finally{setBusy(false)}}
function resolveSolo(){const p:Choice={kind:pitchKinds[Math.floor(Math.random()*3)],zone:zones[Math.floor(Math.random()*3)],style:"유인구"},kh=choice.kind==="아무거나"||(choice.kind==="변화구"&&p.kind!=="직구")||choice.kind===p.kind,zh=choice.zone===p.zone,r=Math.random();let result="헛스윙",runs=0,bases=[...solo.bases],outs=solo.outs,balls=solo.balls,strikes=solo.strikes;if(kh&&zh&&r>.15)result=r>.82?"홈런!":r>.48?"안타!":"파울";else if(kh&&r>.6)result="안타!";else if(r<.2)result="볼";else if(r>.82)result="땅볼 아웃";if(result==="볼"){balls++;if(balls>=4){result="볼넷";bases=[1,bases[0],bases[1]];balls=0;strikes=0}}else if(result==="파울")strikes=Math.min(2,strikes+1);else if(result.includes("아웃")){outs++;balls=0;strikes=0}else if(result==="헛스윙"){strikes++;if(strikes>=3){result="삼진 아웃";outs++;balls=0;strikes=0}}else if(result==="홈런!"){runs=1+bases.reduce((a,b)=>a+b,0);bases=[0,0,0];balls=0;strikes=0}else if(result==="안타!"){runs=bases[2];bases=[1,bases[0],bases[1]];balls=0;strikes=0}let inning=solo.inning,msg=`${p.kind}·${p.zone} — ${result}`;if(outs>=3){outs=0;inning++;bases=[0,0,0];balls=0;strikes=0;msg+=` · ${inning}회로 넘어갑니다.`}setSolo({...solo,inning,outs,balls,strikes,bases,me:solo.me+runs,message:msg,history:[msg,...solo.history].slice(0,5)})}
if(mode==="menu")return <main className="shell"><section className="hero"><div className="brand"><img src="/pitchit-logo-v2.png" alt="PITCHIT"/></div><p className="eyebrow">BASEBALL MIND GAME</p><h1>한 구에 담긴<br/><em>읽고, 속이는 승부.</em></h1><p className="lead">투수와 타자가 동시에 작전을 고르는 3이닝 야구 보드게임. 실력은 숫자로, 승부는 선택으로 결정됩니다.</p><div className="modeGrid"><button className="modeCard red" onClick={()=>setMode("solo")}><Bot/><b>싱글 플레이</b><small>AI와 바로 경기 시작</small></button><button className="modeCard navy" onClick={()=>setMode("quick")}><Radio/><b>빠른 대전</b><small>실시간 자동 매칭</small></button><button className="modeCard cream" onClick={()=>setMode("friend")}><Users/><b>친구와 플레이</b><small>초대 코드로 맞대결</small></button></div><div className="ruleStrip"><span>⚾ 3이닝</span><span>⏱ 동시 선택</span><span>♟ 심리전 중심</span></div></section><div className="ball"/></main>;
if(mode==="quick")return <Lobby title="빠른 대전" icon={<Radio/>} back={()=>setMode("menu")}><p>대기 중인 상대와 자동으로 연결됩니다.</p><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={10}/><button className="primary" onClick={()=>matchmaking("quick")} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Swords/>} 상대 찾기</button></Lobby>;
if(mode==="friend")return <Lobby title="친구와 플레이" icon={<Users/>} back={()=>setMode("menu")}><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={10}/><button className="primary" onClick={()=>matchmaking("create")}>새 경기 만들기</button><div className="or">또는</div><div className="codeRow"><input placeholder="6자리 초대 코드" value={code} onChange={e=>setCode(e.target.value.replace(/[^a-z0-9]/gi,"").slice(0,6).toUpperCase())}/><button onClick={()=>matchmaking("join")} disabled={code.length!==6}>입장</button></div></Lobby>;
if(mode==="solo")return <GameBoard score={[solo.me,solo.ai]} inning={solo.inning} half="초" outs={solo.outs} balls={solo.balls} strikes={solo.strikes} bases={solo.bases} message={solo.message} history={solo.history} choice={choice} setChoice={setChoice} onPlay={resolveSolo} back={()=>setMode("menu")} role="bat"/>;
if(mode==="room"&&match){const batting=(match.half==="top"&&match.role==="away")||(match.half==="bottom"&&match.role==="home");return <GameBoard score={[match.awayScore,match.homeScore]} inning={match.inning} half={match.half==="top"?"초":"말"} outs={match.outs} balls={match.balls} strikes={match.strikes} bases={match.bases} message={match.message} history={match.lastPlay?[`${match.lastPlay.pitch.kind} vs ${match.lastPlay.bat.kind} — ${match.lastPlay.result}`]:[]} choice={choice} setChoice={setChoice} onPlay={submitOnline} back={()=>setMode("menu")} role={batting?"bat":"pitch"} disabled={match.myReady||match.status!=="playing"||busy} roomCode={roomCode||undefined} opponentReady={match.opponentReady}/>}}
function Lobby(p:{title:string;icon:React.ReactNode;back:()=>void;children:React.ReactNode}){return <main className="lobby"><button className="back" onClick={p.back}><ChevronLeft/> 돌아가기</button><section className="lobbyCard"><div className="bigIcon">{p.icon}</div><p className="eyebrow">ONLINE MATCH</p><h2>{p.title}</h2>{p.children}</section></main>}
function GameBoard(p:{score:number[];inning:number;half:string;outs:number;balls:number;strikes:number;bases:number[];message:string;history:string[];choice:Choice;setChoice:(c:Choice)=>void;onPlay:()=>void;back:()=>void;role:Side;disabled?:boolean;roomCode?:string;opponentReady?:boolean}){const kinds=p.role==="pitch"?pitchKinds:batKinds,styles=p.role==="pitch"?["정면승부","유인구","완급조절"]:["강하게","정확하게","지켜보기"];return <main className="game"><header><button className="back" onClick={p.back}><ChevronLeft/></button><div className="miniBrand"><img src="/pitchit-logo-v2.png" alt="PITCHIT"/></div>{p.roomCode?<button className="invite" onClick={()=>navigator.clipboard.writeText(p.roomCode!)}>{p.roomCode}<Copy/></button>:<Shield/>}</header><section className="scoreboard"><div><small>AWAY</small><b>{p.score[0]}</b></div><div className="inning"><strong>{p.inning}회 {p.half}</strong><div className="diamonds"><i className={p.bases[1]?"on":""}/><i className={p.bases[0]?"on":""}/><i className={p.bases[2]?"on":""}/></div></div><div><small>HOME</small><b>{p.score[1]}</b></div></section><div className="field"><div className="mound">{p.role==="pitch"?"P":"⚾"}</div><div className="plate">{p.role==="bat"?"BAT":"C"}</div></div><section className="count"><span>B {[0,1,2,3].map(i=><i key={i} className={i<p.balls?"green":""}/>)}</span><span>S {[0,1,2].map(i=><i key={i} className={i<p.strikes?"yellow":""}/>)}</span><span>O {[0,1,2].map(i=><i key={i} className={i<p.outs?"redDot":""}/>)}</span></section><section className="playPanel"><div className="status"><b>{p.role==="bat"?"타격 작전":"투구 작전"}</b><span>{p.opponentReady?"상대 선택 완료":"상대 선택 대기"}</span></div><Option label={p.role==="pitch"?"구종":"노림 구종"} values={kinds} current={p.choice.kind} select={v=>p.setChoice({...p.choice,kind:v})}/><Option label="코스" values={zones} current={p.choice.zone} select={v=>p.setChoice({...p.choice,zone:v})}/><Option label="승부 방식" values={styles} current={p.choice.style} select={v=>p.setChoice({...p.choice,style:v})}/><button className="pitchBtn" onClick={p.onPlay} disabled={p.disabled}>{p.disabled?"선택 완료 · 상대 대기 중":p.role==="pitch"?"이 공으로 승부":"스윙!"}</button><p className="result">{p.message}</p>{p.history.map((h,i)=><small className="history" key={i}>{h}</small>)}</section></main>}
function Option(p:{label:string;values:string[];current:string;select:(v:string)=>void}){return <div className="option"><label>{p.label}</label><div>{p.values.map(v=><button key={v} className={v===p.current?"selected":""} onClick={()=>p.select(v)}>{v}</button>)}</div></div>}


